### ISSUE TITLE
TypeError: null is not an object (evaluating 'o.signupForm.getValue')

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2663]
Native error in Google Developer Console in Prelaunch-Report:

```
FATAL EXCEPTION: mqt_native_modules
Process: org.pftp, PID: 11148
com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 'o.signupForm.getValue'), stack:
onSignUpClicked@2251:650
onClick@2251:1813
onPress@2268:372
y@112:693
callTimers@112:2718
value@25:3685
<unknown>@25:841
value@25:2939
value@25:813
value@-1
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
	at android.os.Looper.loop(Looper.java:154)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
	at java.lang.Thread.run(Thread.java:761)
```

**Comment by norbertschuler** [comment]
Related to https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/2479
